### PR TITLE
feat(playground): add share button, search filtering, use icons

### PR DESCRIPTION
**Pull request by uncenter**
Adds a share button that copies the URL with query params indicating the selected theme and grammar.

### CODE REVIEW

**Comment by uncenter** [comment]
How can I change the `textContent` of the share button on click to be "Copied!"  for a second or so before reverting back to "Share"?

**Comment by uncenter** [comment]
I got a bit carried away learning Vue... I think I made some good improvements though ahah. Added a simple search functionality, switched to icons instead of text for the buttons (random, github, dark mode) in the header, and of course what this PR was originally for - added a share button.

**Comment by uncenter** [comment]
I'm thinking we could maybe use https://vueuse.org/integrations/useFuse/ for better fuzzy searching? Or is that overcomplicating things. 😆

**Comment by antfu** [comment]
Thanks! I made some refactor. And yes Fuse is nice but indeed overkill in this case

**Pull request merged**
